/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.xueldor.encrypt;

import com.xueldor.encrypt.utils.DigestUtil;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.util.Map;
import javax.swing.JComponent;

/**
 *
 * @author xuexiangyu
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        jTextArea1.setTransferHandler(new DefaultTextTransferHandler(){
            private static final long serialVersionUID = 1L;
            
            @Override
            public boolean importData(JComponent comp, Transferable t) {
                System.out.println("importData");
                try {
                    Object o = t.getTransferData(DataFlavor.javaFileListFlavor);
 
                    String filepath = o.toString();
                    if (filepath.startsWith("[")) {
                        filepath = filepath.substring(1);
                    }
                    if (filepath.endsWith("]")) {
                        filepath = filepath.substring(0, filepath.length() - 1);
                    }
                    String[] split = filepath.split(",");
                    if(split.length > 1){
                        jTextArea1.setText("一次拖入一个文件");
                    }else{
                        filepath = split[0];
                        System.out.println(filepath);
                        jTextArea1.setText(filepath);
                        final String path = filepath;
                        int arithmetic = 0;
                        arithmetic |= jCheckBoxMd5.isSelected()?DigestUtil.MD5:0;
                        arithmetic |= jCheckBoxSha1.isSelected()?DigestUtil.SHA1:0;
                        arithmetic |= jCheckBoxSha256.isSelected()?DigestUtil.SHA256:0;
                        arithmetic |= jCrc32CheckBox1.isSelected()?DigestUtil.CRC32:0;
                        final int arithmeticSel = arithmetic;
                        new Thread(new Runnable(){
                            @Override
                            public void run() {
                                long start = System.currentTimeMillis();
                                Map<String,String> map = DigestUtil.getFileDigests(path,arithmeticSel,new DigestUtil.Progress() {
                                    @Override
                                    public void onProgress(int prog) {
                                        jProgressBar1.setValue(prog);
                                    }
                                });
                                long end = System.currentTimeMillis();
                                for (Map.Entry<String, String> entry : map.entrySet()) {
                                    String arithName = entry.getKey();
                                    String arithValue = entry.getValue();
                                    jTextArea1.append("\n" + arithName + ": " + arithValue);
                                }
                                
                                jTextArea1.append("\nCost: " + (end - start)/1000.0f + "s");
                            }
                        }).start();
                        
                    }
                    return true;
                }
                catch (Exception e) {
                    jTextArea1.setText(e.getLocalizedMessage());
                }
                return false;
            }
            @Override
            public boolean canImport(JComponent comp, DataFlavor[] flavors) {
                for (int i = 0; i < flavors.length; i++) {
                    if (DataFlavor.javaFileListFlavor.equals(flavors[i])) {
                        return true;
                    }
                }
                return false;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jProgressBar1 = new javax.swing.JProgressBar();
        jCheckBoxMd5 = new javax.swing.JCheckBox();
        jCheckBoxSha1 = new javax.swing.JCheckBox();
        jCheckBoxSha256 = new javax.swing.JCheckBox();
        jnextButton1 = new javax.swing.JButton();
        jCrc32CheckBox1 = new javax.swing.JCheckBox();
        jRenameButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("请拖拽文件到这里...");
        jScrollPane1.setViewportView(jTextArea1);

        jCheckBoxMd5.setSelected(true);
        jCheckBoxMd5.setText("MD5");

        jCheckBoxSha1.setText("SHA-1");

        jCheckBoxSha256.setSelected(true);
        jCheckBoxSha256.setText("SHA-256");

        jnextButton1.setText("下一页");
        jnextButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnextButton1ActionPerformed(evt);
            }
        });

        jCrc32CheckBox1.setText("CRC32");

        jRenameButton1.setText("文件重命名");
        jRenameButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRenameButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxMd5)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxSha1)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxSha256)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCrc32CheckBox1)
                        .addGap(0, 395, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jRenameButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jnextButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxMd5)
                    .addComponent(jCheckBoxSha1)
                    .addComponent(jCheckBoxSha256)
                    .addComponent(jCrc32CheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jnextButton1)
                    .addComponent(jRenameButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jnextButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnextButton1ActionPerformed
        dispose();
        new EncryptJFrame().setVisible(true);
    }//GEN-LAST:event_jnextButton1ActionPerformed

    private void jRenameButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRenameButton1ActionPerformed
        dispose();
        new RenameJFrame().setVisible(true);
    }//GEN-LAST:event_jRenameButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {        
        try { 
            if(System.getProperties().getProperty("os.name").toUpperCase().indexOf("WINDOWS") != -1){
               //windows
               javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); // Windows风格 
            }else{
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                   if ("Nimbus".equals(info.getName())) {
                       javax.swing.UIManager.setLookAndFeel(info.getClassName());
                       break;
                   }
               }
            }
        } catch (ClassNotFoundException ex) { 
            ex.printStackTrace(); 
        } catch (InstantiationException ex) { 
            ex.printStackTrace(); 
        } catch (IllegalAccessException ex) { 
            ex.printStackTrace(); 
        } catch (javax.swing.UnsupportedLookAndFeelException ex) { 
            ex.printStackTrace(); 
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxMd5;
    private javax.swing.JCheckBox jCheckBoxSha1;
    private javax.swing.JCheckBox jCheckBoxSha256;
    private javax.swing.JCheckBox jCrc32CheckBox1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JButton jRenameButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jnextButton1;
    // End of variables declaration//GEN-END:variables
}
